name: Repository Maintenance

on:
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .ali/**
      - docs/**
      - action.yml
      - .github/workflows/shared-workflow.yaml

jobs:
  repository-maintenance:
    name: Repository Maintenance
    uses: acceleratelearning/workflow-repository-maintenance/.github/workflows/shared-workflow.yaml@v1
  